version: '3.7'
services:

  db:
    image: postgres:16.0-alpine3.18
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev
      # - .env

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
      # - 6379

  app:
    build: 
      context: .
    env_file:
      - .env-non-dev
      # - .env
    container_name: exchange_app
    command: bash -c "cd docker/ && bash app.sh"
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis
