version: '3.7'
services:

  db:
    image: postgres:16.0-alpine3.18
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    env_file:
      - ../back/.env-non-dev
      # - .env

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
      # - 6379

  backend:
    build: 
      context: ../back/
    env_file:
      - ../back/.env-non-dev
      # - .env
    container_name: backend_app
    command: bash -c "alembic upgrade head && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ../front/
    container_name: frontend_app
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
