"""image payment option

Revision ID: 272bb25771ac
Revises: 71eafc9e83b1
Create Date: 2023-10-09 18:58:33.011662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272bb25771ac'
down_revision: Union[str, None] = '71eafc9e83b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'service_sell_po_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('order', 'service_buy_po_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'service_buy_po_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('order', 'service_sell_po_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
