"""create tables

Revision ID: 30f2bd421d1a
Revises: 
Create Date: 2023-08-13 21:15:32.652707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f2bd421d1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('gas', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tikker', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tikker')
    )
    op.create_table('pending_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('get_value', sa.Float(), nullable=False),
    sa.Column('send_value', sa.Float(), nullable=False),
    sa.Column('cc_num', sa.BigInteger(), nullable=False),
    sa.Column('cc_holder', sa.Text(), nullable=False),
    sa.Column('cc_image_name', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Canceled', 'InProcess', 'Approved', name='pendingstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('registered_on', sa.TIMESTAMP(), nullable=False),
    sa.Column('role', sa.Enum('User', 'Moderator', 'Admin', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('payment_option',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('banking_acc_number', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['currency.tikker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banking_acc_number'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('ammount_get', sa.Float(), nullable=False),
    sa.Column('get_currency', sa.Text(), nullable=False),
    sa.Column('ammount_give', sa.Float(), nullable=False),
    sa.Column('give_currency', sa.Text(), nullable=False),
    sa.Column('payment_option', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Canceled', 'Timeout', 'Completed', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['get_currency'], ['currency.tikker'], ),
    sa.ForeignKeyConstraint(['give_currency'], ['currency.tikker'], ),
    sa.ForeignKeyConstraint(['payment_option'], ['payment_option.name'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('payment_option')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('pending_order')
    op.drop_table('currency')
    op.drop_table('commissions')
    # ### end Alembic commands ###
