"""changed str method on currency

Revision ID: 3a5fc749dce5
Revises: 7ee2cfe011b6
Create Date: 2023-09-04 14:59:24.357620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5fc749dce5'
down_revision: Union[str, None] = '7ee2cfe011b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
