"""revie fk fix

Revision ID: 47793d5839c8
Revises: e5ddadddf6e8
Create Date: 2023-10-11 16:19:22.790905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47793d5839c8'
down_revision: Union[str, None] = 'e5ddadddf6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_user_email_fkey', 'review', type_='foreignkey')
    op.drop_column('review', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.create_foreign_key('review_user_email_fkey', 'review', 'user', ['user_email'], ['email'])
    # ### end Alembic commands ###
