"""added new model commission

Revision ID: 52e1cafc519f
Revises: efbb1d4bb630
Create Date: 2023-08-12 15:04:41.278781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e1cafc519f'
down_revision: Union[str, None] = 'efbb1d4bb630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('gas', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commissions')
    # ### end Alembic commands ###
