"""payment_options

Revision ID: 57b976b72e8d
Revises: f4fd5974362c
Create Date: 2023-09-15 11:42:35.546728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b976b72e8d'
down_revision: Union[str, None] = 'f4fd5974362c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_option_completed_order_id_fkey', 'payment_option', type_='foreignkey')
    op.drop_column('payment_option', 'completed_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_option', sa.Column('completed_order_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_option_completed_order_id_fkey', 'payment_option', 'completed_order', ['completed_order_id'], ['id'])
    # ### end Alembic commands ###
