"""change relation to one to many

Revision ID: 6201b4ceb10f
Revises: 3a5fc749dce5
Create Date: 2023-09-04 15:09:19.591368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6201b4ceb10f'
down_revision: Union[str, None] = '3a5fc749dce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
