"""image payment option

Revision ID: 71eafc9e83b1
Revises: 1d1481d6e797
Create Date: 2023-10-09 17:25:57.253666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71eafc9e83b1'
down_revision: Union[str, None] = '1d1481d6e797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_option', 'image',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_option', 'image',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
