"""changed relation from currency to servise_pm

Revision ID: 7ee2cfe011b6
Revises: f0f22dc77c78
Create Date: 2023-09-04 14:56:07.126783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee2cfe011b6'
down_revision: Union[str, None] = 'f0f22dc77c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('currency_service_pm_id_fkey', 'currency', type_='foreignkey')
    op.drop_column('currency', 'service_pm_id')
    op.add_column('service_pm', sa.Column('currency_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'service_pm', 'currency', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_pm', type_='foreignkey')
    op.drop_column('service_pm', 'currency_id')
    op.add_column('currency', sa.Column('service_pm_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('currency_service_pm_id_fkey', 'currency', 'service_pm', ['service_pm_id'], ['id'])
    # ### end Alembic commands ###
