"""payment opt

Revision ID: 8c69e48fe7bc
Revises: 57b976b72e8d
Create Date: 2023-09-15 12:54:09.894246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c69e48fe7bc'
down_revision: Union[str, None] = '57b976b72e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_option', sa.Column('completed_order_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'payment_option', 'completed_order', ['completed_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_option', type_='foreignkey')
    op.drop_column('payment_option', 'completed_order_id')
    # ### end Alembic commands ###
