"""user order relations

Revision ID: b1757cef5570
Revises: ff9bcbbe72b8
Create Date: 2023-10-11 16:55:25.071419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1757cef5570'
down_revision: Union[str, None] = 'ff9bcbbe72b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###
