"""currency id

Revision ID: d82f555e42cd
Revises: a2ce26db91d7
Create Date: 2023-10-10 21:15:41.496317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82f555e42cd'
down_revision: Union[str, None] = 'a2ce26db91d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_payment_option', sa.Column('currency_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('service_payment_option_currency_tikker_fkey', 'service_payment_option', type_='foreignkey')
    op.create_foreign_key(None, 'service_payment_option', 'currency', ['currency_id'], ['id'])
    op.drop_column('service_payment_option', 'currency_tikker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_payment_option', sa.Column('currency_tikker', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_payment_option', type_='foreignkey')
    op.create_foreign_key('service_payment_option_currency_tikker_fkey', 'service_payment_option', 'currency', ['currency_tikker'], ['tikker'])
    op.drop_column('service_payment_option', 'currency_id')
    # ### end Alembic commands ###
