"""repr and str for currency and spo

Revision ID: e656bf60ffa3
Revises: 7ac8998379f8
Create Date: 2023-10-11 13:36:26.412371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e656bf60ffa3'
down_revision: Union[str, None] = '7ac8998379f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
