"""Changed relationships on curency and servise pm

Revision ID: f0f22dc77c78
Revises: f50f341ffc06
Create Date: 2023-09-04 14:45:07.284572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f22dc77c78'
down_revision: Union[str, None] = 'f50f341ffc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('service_pm_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'currency', 'service_pm', ['service_pm_id'], ['id'])
    op.alter_column('pending_order', 'user_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('service_pm_currency_fkey', 'service_pm', type_='foreignkey')
    op.drop_column('service_pm', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_pm', sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key('service_pm_currency_fkey', 'service_pm', 'currency', ['currency'], ['tikker'])
    op.alter_column('pending_order', 'user_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'currency', type_='foreignkey')
    op.drop_column('currency', 'service_pm_id')
    # ### end Alembic commands ###
