"""add new fields

Revision ID: f50f341ffc06
Revises: 5c1041579818
Create Date: 2023-09-01 16:04:53.200153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50f341ffc06'
down_revision: Union[str, None] = '5c1041579818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_option_cc_num_x_wallet_key', 'payment_option', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('payment_option_cc_num_x_wallet_key', 'payment_option', ['cc_num_x_wallet'])
    # ### end Alembic commands ###
