"""po user relations fix

Revision ID: ff9bcbbe72b8
Revises: 47793d5839c8
Create Date: 2023-10-11 16:22:50.390394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9bcbbe72b8'
down_revision: Union[str, None] = '47793d5839c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_option', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'payment_option', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_option', type_='foreignkey')
    op.drop_column('payment_option', 'user_id')
    # ### end Alembic commands ###
